openapi: 3.0.0
info:
  title: Organization API
  version: 1.0.0
tags:
  - name: Organizations
    description: Операции, связанные с организациями
  - name: OrgManager
    description: Операции второго сервиса
paths:
  /organizations:
    get:
      tags:
        - Organizations
      summary: Получение списка всех организаций
      operationId: getOrganizations
      parameters:
        - name: creationDate
          in: query
          description: Фильтр по дате создания организации (где дата - дата, после которой создана организация)
          required: false
          schema:
              type: string
              format: date
        - name: annualTurnover
          in: query
          description: Фильтр по годовому обороту организации (где - это меньше указанного значения)
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
        - name: sort
          in: query
          description: Поле для сортировки и направление (пример:name,asc или creationDate,desc)
          required: false
          schema:
            type: string
            example: "asc(name)"
      responses:
        '200':
          description: Успешный ответ с массивом организаций
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '400':
          description: Ошибка в запросе. Неправильно, попробуй ещё
        '500':
          description: Внутренняя ошибка сервера
    post:
      tags:
        - Organizations
      summary: Добавление новой организации
      operationId: createOrganization
      requestBody:
        description: Объект новой организации
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '201':
          description: Организация успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: Некорректный запрос
        '500':
          description: Внутренняя ошибка сервера

  /organizations/{id}:
    get:
      tags:
        - Organizations
      summary: Получение организации по ID
      operationId: getOrganizationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
          description: Уникальный идентификатор организации
      responses:
        '200':
          description: Успешный ответ с объектом организации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '404':
          description: Организация с указанным ID не найдена
        '500':
          description: Внутренняя ошибка сервера

    put:
      tags:
        - Organizations
      summary: Обновление организации по ID
      operationId: updateOrganizationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
          description: Уникальный идентификатор организации
      requestBody:
        description: Обновленные данные организации
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: Организация успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '404':
          description: Организация с указанным ID не найдена
        '400':
          description: Некорректный запрос
        '500':
          description: Внутренняя ошибка сервера

    delete:
      tags:
        - Organizations
      summary: Удаление организации по ID
      operationId: deleteOrganizationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
          description: Уникальный идентификатор организации
      responses:
        '204':
          description: Организация успешно удалена
        '404':
          description: Организация с указанным ID не найдена
        '500':
          description: Внутренняя ошибка сервера

  /organizations/group-by-address:
    get:
      tags:
        - Organizations
      summary: Группировка объектов по значению поля officialAddress и возврат количества элементов в каждой группе
      operationId: groupByOfficialAddress
      responses:
        '200':
          description: Группировка выполнена успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    officialAddress:
                      $ref: '#/components/schemas/Address'
                    count:
                      type: integer
                      description: "Количество организаций в группе с данным адресом"
        '400':
          description: Ошибка в запросе
        '500':
          description: Внутренняя ошибка сервера

  /organizations/count-by-employees:
    get:
      tags:
        - Organizations
      summary: Возвращает количество организаций, у которых значение поля employeesCount больше заданного
      operationId: countByEmployeesCount
      parameters:
        - name: count
          in: query
          required: true
          schema:
            type: integer
            format: int32
            description: "Значение количества сотрудников, с которым будет происходить сравнение"
      responses:
        '200':
          description: Количество объектов успешно возвращено
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: "Количество организаций, у которых число сотрудников больше заданного"
        '400':
          description: Ошибка в запросе
        '500':
          description: Внутренняя ошибка сервера

  /organizations/search-by-fullname:
    get:
      tags:
        - Organizations
      summary: Поиск организаций по подстроке в поле fullName
      operationId: searchByFullName
      parameters:
        - name: substring
          in: query
          required: true
          schema:
            type: string
            description: "Подстрока, которая будет искаться в поле fullName"
      responses:
        '200':
          description: Массив объектов, соответствующих критерию поиска
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '400':
          description: Некорректный запрос
        '500':
          description: Внутренняя ошибка сервера

  /orgmanager/merge/{id1}/{id2}/{new-name}/{new-address}:
    post:
      tags:
        - OrgManager
      summary: Объединить две организации
      description: Объединить две организации, создав новую с заданным именем и адресом, и зачислив в неё всех сотрудников исходных организаций.
      parameters:
        - name: id1
          in: path
          description: ID первой организации
          required: true
          schema:
            type: integer
        - name: id2
          in: path
          description: ID второй организации
          required: true
          schema:
            type: integer
        - name: new-name
          in: path
          description: Новое имя объединённой организации
          required: true
          schema:
            type: string
        - name: new-address
          in: path
          description: Новый адрес объединённой организации
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Организации успешно объединены
          content:
            application/json:
              schema:
                type: object
                properties:
                  newOrgId:
                    type: integer
                    description: ID новой объединённой организации
                  message:
                    type: string
                    example: "Организации успешно объединены"
        '400':
          description: Ошибка валидации параметров
        '404':
          description: Одна или обе организации не найдены
        '500':
          description: Внутренняя ошибка сервера
    servers:
      - url: /orgmanager

  /orgmanager/hire/{id}:
    post:
      tags:
        - OrgManager
      summary: Добавить нового сотрудника в организацию
      description: Добавить нового сотрудника в организацию по её ID.
      parameters:
        - name: id
          in: path
          description: ID организации, в которую добавляется новый сотрудник
          required: true
          schema:
            type: integer
      requestBody:
        description: Информация о новом сотруднике
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeName:
                  type: string
                  description: Имя сотрудника
                  example: "Иван Иванов"
                position:
                  type: string
                  description: Должность сотрудника
                  example: "Менеджер"
      responses:
        '200':
          description: Сотрудник успешно добавлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  employeeId:
                    type: integer
                    description: ID нового сотрудника
                  message:
                    type: string
                    example: "Сотрудник успешно добавлен"
        '400':
          description: Ошибка валидации данных сотрудника
        '404':
          description: Организация не найдена
        '500':
          description: Внутренняя ошибка сервера
    servers:
      - url: /orgmanager


components:
  schemas:
    Organization:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: "Уникальный идентификатор, генерируется автоматически, значение должно быть больше 0."
          minimum: 1
        name:
          type: string
          description: "Название организации, не может быть null или пустой строкой."
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date
          description: "Дата создания организации, генерируется автоматически, не может быть null."
        annualTurnover:
          type: integer
          format: int32
          description: "Годовой оборот организации, значение должно быть больше 0."
          minimum: 1
        fullName:
          type: string
          description: "Полное название организации, не может быть пустым или длиной более 1678 символов."
          maxLength: 1678
        employeesCount:
          type: integer
          format: int32
          description: "Количество сотрудников, не может быть null и должно быть больше 0."
          minimum: 1
        type:
          $ref: '#/components/schemas/OrganizationType'
        officialAddress:
          $ref: '#/components/schemas/Address'
      required:
        - id
        - name
        - coordinates
        - creationDate
        - annualTurnover
        - fullName
        - employeesCount
        - type
        - officialAddress

    Coordinates:
      type: object
      properties:
        x:
          type: integer
          format: int32
          description: "Координата X, максимальное значение 76, не может быть null."
          maximum: 76
        y:
          type: integer
          format: int32
          description: "Координата Y, значение должно быть больше -155 и не может быть null."
          minimum: -155
      required:
        - x
        - y

    Address:
      type: object
      properties:
        zipCode:
          type: string
          description: "Почтовый индекс. Может быть null."
    
    OrganizationType:
      type: string
      enum:
        - PUBLIC
        - TRUST
        - OPEN_JOINT_STOCK_COMPANY
      description: "Тип организации."

