server:
  port: 8776

zuul:
  routes:
    org-manager:
      path: /orgmanager/**
      url: http://localhost:8889/orgmanager
    org-service:
      path: /org-service/api/**
      url: http://localhost:8080//org-service/api

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: api-gateway
