spring.application.name: org-manager

logging:
  level:
    root: INFO
    soa.lab2: DEBUG
    feign: DEBUG
    org.eclipse.jetty: INFO
    org.springframework.boot.web.embedded.jetty: INFO
    org:
      springframework:
        cloud:
          openfeign: DEBUG
  file:
    name: logs/myapp.log


server:
  port: 28791
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
    key-store-type: JKS
  jetty:
    ssl:
      sni-host-check: false

