server:
  port: 8889

spring:
  application:
    name: org-manager

eureka:
  instance:
    network-interface: eth0
    hostname: localhost
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetchRegistry: true
