server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShchA317/SOA.git
          basedir: lab3/config-service
          search-paths: '{application}'
          default-label: main
          clone-on-start: true
          force-pull: true
