server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: github.com/ShchA317/SOA/lab3/config-server
          default-label: main
          search-paths: "{application}"
