server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShchA317/SOA/
          default-label: main
          search-paths: lab3/config-service/src/main/resources/org-manager
